# Generated by Django 4.0.5 on 2022-06-29 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlr_auth.category', verbose_name='Category '),
        ),
    ]
