# Generated by Django 4.0.5 on 2022-06-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0002_profile_birthdate_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
