# Generated by Django 4.0.5 on 2022-07-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0002_review_reviewworkerrating_serviceproviderprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile-pictures-service-providers/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='image'),
        ),
    ]
