# Generated by Django 4.0.5 on 2022-06-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0003_alter_category_options_alter_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='workerprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
