# Generated by Django 4.0.5 on 2022-06-26 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0004_profile_profile_picture_alter_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='service type')),
            ],
            options={
                'verbose_name': 'service type',
                'verbose_name_plural': 'services type',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, verbose_name='service title')),
                ('time', models.CharField(max_length=10000, verbose_name='time')),
                ('price', models.FloatField(verbose_name='service cost')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlr_auth.category', verbose_name='service type')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('-date',),
            },
        ),
    ]
