# Generated by Django 4.0.5 on 2022-07-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0004_alter_serviceproviderprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-date',), 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
