# Generated by Django 4.0.5 on 2022-06-29 20:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vlr_auth', '0005_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceproviderprofile',
            options={'ordering': ('-date',), 'verbose_name': 'service provider', 'verbose_name_plural': 'service providers'},
        ),
        migrations.RenameModel(
            old_name='WorkerProfile',
            new_name='ServiceProviderProfile',
        ),
        migrations.CreateModel(
            name='ReviewWorkerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlr_auth.serviceproviderprofile')),
            ],
        ),
    ]
