# Generated by Django 4.0.5 on 2022-06-26 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0005_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10000, unique=True, verbose_name='worker first name')),
                ('last_name', models.CharField(max_length=10000, unique=True, verbose_name='worker last name')),
                ('username', models.CharField(max_length=10000, unique=True, verbose_name='worker last name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone no.')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='secondary phone no.')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.TextField(verbose_name='address')),
                ('years_of_exp', models.IntegerField(max_length=2, verbose_name='experience')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'worker',
                'verbose_name_plural': 'workers',
                'ordering': ('-date',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vlr_auth.category', verbose_name='service type'),
        ),
    ]
