# Generated by Django 4.0.5 on 2022-06-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0006_worker_alter_category_options_delete_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='years_of_exp',
            field=models.IntegerField(verbose_name='experience'),
        ),
    ]
