# Generated by Django 4.0.5 on 2022-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0007_alter_worker_years_of_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='username',
            field=models.CharField(max_length=10000, unique=True, verbose_name='username'),
        ),
    ]
