# Generated by Django 4.0.5 on 2022-07-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0008_serviceproviderprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewworkerrating',
            name='service_provider',
            field=models.CharField(default=None, help_text='servicer_provider', max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewworkerrating',
            name='username',
            field=models.CharField(default=None, help_text='username', max_length=100),
        ),
    ]
