# Generated by Django 4.0.5 on 2022-07-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0009_alter_reviewworkerrating_service_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/<django.db.models.fields.related.OneToOneField>/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/<django.db.models.fields.CharField><django.db.models.fields.CharField>/', verbose_name='image'),
        ),
    ]
