# Generated by Django 4.0.5 on 2022-06-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlr_auth', '0011_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
